In [28]:
import pandas as pd

In [35]:
doc1 = pd.read_csv('../data/generated_outputs/doc1.csv')
doc2 = pd.read_csv('../data/generated_outputs/doc2.csv')
doc3 = pd.read_csv('../data/generated_outputs/doc3.csv')
doc4 = pd.read_csv('../data/generated_outputs/doc4.csv')
doc5 = pd.read_csv('../data/generated_outputs/doc5.csv')

In [36]:
doc1

,Date Added,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Likelihood (1-10) (pre-mitigation),Impact (1-10) (pre-mitigation),Risk Priority (pre-mitigation),Mitigating Action,Likelihood (1-10) (post-mitigation),Impact (1-10) (post-mitigation),Risk Priority (post-mitigation)
0,21-Feb-17,1,Data sharing from BBSRI at risk,Pre Construction,Technology Development,Environmental,4.0,2.0,Low,facilitate conversations with Umaine on data s...,3.0,1.0,Low
1,21-Feb-17,2,Ice data collection unsuccessful,Construction Commissioning,Technology Development,Uaa Lead,3.0,3.0,Low,real time data collection implemented,1.0,2.0,Low
2,21-Feb-17,3,Appropriate permits and licenses procured in t...,Construction Commissioning,Planning,Environmental,4.0,4.0,Low,FERC Final license application submittal scheu...,3.0,4.0,Low
3,21-Feb-17,4,Wet Gap Generator design not yet complete,Construction,Technology Development,Lead Engineer,4.0,3.0,Low,Design reviews and component validation testing,2.0,3.0,Low
4,21-Feb-17,5,Timing of generator procurement from IKM could...,Construction,Procurement,Lead Engineer,4.0,3.0,Low,Ensure Generator delivery by 2/2018 to allow a...,3.0,3.0,Low
5,21-Feb-17,6,components are not available,Construction,Procurement,Lead Engineer,2.0,2.0,Low,Compile BOM and ascertain component lead times...,1.0,3.0,Low
6,21-Feb-17,7,Fabricated components have significant lead times,Construction,Procurement,Lead Engineer,3.0,3.0,Low,"Frequent vendor communication , issue PO with ...",2.0,3.0,Low
7,21-Feb-17,8,Fabricated components have significant lead times,Construction,Procurement,Lead Engineer,4.0,3.0,Low,"Frequent vendor communication , issue PO with ...",2.0,3.0,Low
8,21-Feb-17,9,Singel source vendor for some components that ...,Construction,Procurement,Project Management,4.0,3.0,Low,"Frequent vendor communication , issue PO with ...",3.0,3.0,Low
9,21-Feb-17,10,"components are not available, integration of ...",Construction,Technology Development,Lead Engineer,4.0,3.0,Low,Compile BOM and ascertain component lead times...,3.0,3.0,Low
10,21-Feb-17,11,Fabrication delays and out of spec delivered p...,Construction,Procurement,Project Management,4.0,3.0,Low,Compile BOM and ascertain component lead times...,3.0,3.0,Low
11,21-Feb-17,12,components are not available,Construction,Procurement,Lead Engineer,3.0,3.0,Low,Compile BOM and ascertain component lead times...,1.0,3.0,Low
12,21-Feb-17,13,Custom components require fabrication lead time,Construction,Procurement,Lead Engineer,4.0,3.0,Low,"Frequent vendor communication , issue PO with ...",2.0,3.0,Low
13,21-Feb-17,14,Custom components require fabrication lead time,Construction,Procurement,Lead Engineer,4.0,3.0,Low,"Frequent vendor communication , issue PO with ...",2.0,3.0,Low
14,21-Feb-17,15,Custom components require fabrication lead time,Construction,Procurement,Lead Engineer,4.0,3.0,Low,"Frequent vendor communication , issue PO with ...",2.0,3.0,Low
15,21-Feb-17,16,Buoyancy System fails some or all of validatio...,Construction Commissioning,Technology Development,Lead Engineer,3.0,4.0,Low,Utilizing Incremetnal improvements to a proven...,2.0,3.0,Low
16,21-Feb-17,17,Sturctural Assembly fails some or all of vali...,Construction Commissioning,Technology Development,Lead Engineer,3.0,4.0,Low,FEA analysis of structure include load factors...,2.0,3.0,Low
17,21-Feb-17,18,Turbine Assembly fails some or all of validati...,Construction Commissioning,Technology Development,Lead Engineer,3.0,3.0,Low,Utilize CFD as design tool for performance val...,2.0,3.0,Low
18,21-Feb-17,19,Genertor fails some or all of validation tests,Commissioning,Technology Development,Lead Engineer,4.0,3.0,Low,Factory Accpetance testing and laboratory test...,2.0,3.0,Low
19,21-Feb-17,20,Power Electronics fails validation,Construction Commissioning,Technology Development,Project Management,4.0,3.0,Low,Factory accpetance tests and sequenced laborat...,3.0,3.0,Low
20,21-Feb-17,21,SCADA system fails validation,Construction Commissioning,Technology Development,Lead Engineer,4.0,3.0,Low,Factory accpetance tests and sequenced laborat...,3.0,3.0,Low
21,21-Feb-17,22,Power and data cables failure,Construction,Deployment,Project Management,3.0,4.0,Low,Utilize proven cable technology utilize second...,2.0,4.0,Low
22,21-Feb-17,23,Mooring system failure,Construction Commissioning,Deployment,Lead Engineer,3.0,5.0,Low,"Design to DNV standards, utilize geophyisical ...",2.0,5.0,Low
23,21-Feb-17,24,Driveline failure,Construction,Technology Development,Lead Engineer,4.0,4.0,Low,"Throught validation testing, desing system for...",3.0,4.0,Low
24,21-Feb-17,25,Mechanical Brake Failure,Construction,Technology Development,Lead Engineer,4.0,4.0,Low,"Throught validation testing, redundant electri...",3.0,3.0,Low
25,24-Feb-17,26,Reciept of FERC Pilot license or permits are d...,Construction Commissioning,Regulatory,Environmental,4.0,5.0,Low,Continue regular dialogue with regulatory agen...,3.0,5.0,Low
26,24-Feb-17,27,Component shipment to Igiugig is delayed due t...,Construction,Procurement,Project Management,3.0,4.0,Low,"Track project schedule, align component valida...",2.0,4.0,Low
27,24-Feb-17,28,Device assembly difficult or requires modifica...,Construction,Technology Development,Lead Engineer,3.0,4.0,Low,Device assembly is fdifficult or requires work...,2.0,4.0,Low
28,24-Feb-17,29,Power System deployment/comissioning encounter...,Construction Commissioning,Execution,Project Management,3.0,5.0,Low,prior device testing and component testing in ...,2.0,5.0,Low
29,24-Feb-17,30,Ice accumlation on or interaction with device ...,Construction Commissioning,Operations,Lead Engineer,4.0,5.0,Low,Collection of in river ice data for 2 years pr...,3.0,5.0,Low
30,24-Feb-17,31,Salmon smolt data collection shows adverse rea...,Construction Commissioning,Environmental,Environmental,4.0,4.0,Low,Develop rigorous fish monitroing pland in budg...,3.0,4.0,Low
31,24-Feb-17,32,Device removal complicated by technological or...,Construction Commissioning,Deployment,Project Management,3.0,5.0,Low,Buoyancy system includes redundant and isoalte...,2.0,5.0,Low
32,24-Feb-17,33,Higher cost for maintenance and logistical sup...,Construction Commissioning,Operations,Project Management,4.0,4.0,Low,Developing system requirements will be critica...,2.0,2.0,Low

In [34]:
doc2

,Date Added,Risk ID,Risk Description,Project Stage,Project Category,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)",Risk Owner,Mitigating Action,Result
0,NaN,3,Failure to discharge planning and listed build...,Pre Construction,Design,3.333333,1.666667,Low,Project Manager,NaN,Design team and contractor to collate initial ...
1,NaN,4,Planning conditions impact on budget,Pre Construction,Planning,6.666667,5.000000,Med,Project Manager,Increase project budget,Extent of conditions known and to be reviewed ...
2,NaN,10,Electricity provider works delayed or non-conf...,Construction,Design,3.333333,3.333333,Low,Project Manager,Works to provide new supply are\ndelayed / not...,Orders for the electrical services have been p...
3,NaN,11,Building Control Sign Off delay due to\nlack o...,Construction,Design,3.333333,3.333333,Low,Project Manager,Revisit design to address concerns of building...,Continue liaison with the Building Control Off...
4,NaN,12,Impact of boat companies (City Cruises),Pre Construction,Design,3.333333,1.666667,Low,Project Manager,Impact delivery/ site servicing strategy.,Legal agreements are in place
5,NaN,13,Party wall negotiations & construction access,Pre Construction,Construction,5.000000,6.666667,Med,Project Manager,Objection from neighbours. Potential\ndelay to...,Appoint party wall surveyor and progress discu...
6,NaN,14,Failure to secure market interest for restaura...,Pre Construction,Procurement,5.000000,8.333333,Med,Project Manager,Restaurant not achieving appropriate\ntenant a...,Early engagement of agent for potential lettin...
7,NaN,16,Increased construction costs,Construction,Construction,5.000000,5.000000,Med,Project Manager,Exchange rate on materials. Impact of\ninterna...,Tender prices received and under review - Risk...
8,NaN,18,Sub-contractor insolvency,Pre Construction,Procurement,6.666667,5.000000,Med,Construction Manager,Impacts Main Contractor,Contractor financial checks and vetting of sub...
9,NaN,20,Surveys required to determine ground\nconditio...,Pre Construction,Pre-construction,1.666667,8.333333,Low,Lead Engineer,Possible need to re-visit design / deal\nwith ...,"GI survey undertaken, information\nobtained. C..."
10,NaN,21,Identification of active movement,Construction,Structural,1.666667,8.333333,Low,Structural Engineer,"Proven to be active, remediation\nimpacts cost",Ongoing monitoring by ARUP and monitoring spec...
11,NaN,22,Unidentified archaeology,Pre Construction,Design,3.333333,3.333333,Low,Environment Lead,Further evaluation required. Cost impact,Evaluation of site undertaken
12,NaN,23,Additional surveys required,Pre Construction,Pre-construction,1.666667,1.666667,Low,Project Manager,Cost impact,Undertake outstanding surveys
13,NaN,26,Unrealistic programme submitted by contractor,Pre Construction,Procurement,1.666667,5.000000,Low,Project Manager,-,Market tested
14,NaN,27,Programme delays; due to flood levels\nimpacti...,Construction,Structural,10.000000,8.333333,High,Project Manager / Environment Lead,"Works stop, cost and programme implications",Review historic flood data and issue to Contra...
15,NaN,29,Delay to design programme,Pre Construction,Design,5.000000,5.000000,Med,Design Manager,Client/ Contractor impact cost/\nprogramme,Implementation of IRS schedules design deliver...
16,NaN,31,"Underpinning, piling and crack repairs\nto be ...",Construction,Design,5.000000,8.333333,Med,Structural Engineer,May resolve existing cracks and\nmovement of t...,"Detailed dilapidations surveys, crack monitors"
17,NaN,32,Discovering structural unknowns,Pre Construction,Structural,8.333333,6.666667,High,Structural Engineer,Costs of additional surveys and\nremediation w...,Undertake surveys early to determine unknowns....
18,NaN,35,Undetected services not identified on surveys ...,Pre Construction,Design,3.333333,5.000000,Low,Lead Engineer,Programme/ re-design/ cost impact to\naddress ...,Utilities surveys maps obtained and plotted on...
19,NaN,40,River source heat pump license approval by the...,Pre Construction,Planning,1.666667,6.666667,Low,Environment Lead,Delay in no approval from EA,Provisional consent obtained; continued dialog...
20,NaN,41,Sourcing stone for remediation works,Pre Construction,Procurement,6.666667,5.000000,Med,Procurement Manager,Quarry that stone exists from is closed. Impac...,Investigate other quarries which supply the st...
21,NaN,42,Structural damage and the repairs required to ...,Construction,Structural,6.666667,6.666667,Med,Structural Engineer,Finding the right solution to undertake\nthe u...,Bullivants / Arup design and Vinci\ntemporary ...
22,NaN,48,Outstanding defects remaining unresolved,Construction,Commissioning,3.333333,5.000000,Low,Project Manager,CYC left with legacy issues and building\ndefe...,Ability to resolve within the building contrac...
23,NaN,50,Costs exceeds allocated budget (Non Constructi...,Pre Construction,Procurement,8.333333,5.000000,Med,Project Manager,"Particular risks surrounding consultant\nfees,...",Review non construction costs prior to contrac...
24,NaN,51,Incorrect estimation design errors and ambigu...,Pre Construction,Design,5.000000,5.000000,Med,Design Manager,Construction cost overrun,Risk sits with CYC except CDP items
25,NaN,56,Availability of specialist labour / equipment,Pre Construction,Procurement,5.000000,5.000000,Med,Project Manager,Change in specification / need to appoint spe...,Dialogue with main contractor & supply chain
26,NaN,61,Poor co-ordination with design team interfaces...,Pre Construction,Design,3.333333,5.000000,Low,Design Manager,-,CDP requirements have reduced from initial int...
27,NaN,62,Rights of Light,Pre Construction,Design,1.666667,6.666667,Low,Project Manager,-,Title report does not identify any issues
28,NaN,64,Poor contractor performance during construction,Construction,Construction,3.333333,8.333333,Med,Project Manager,-,Contract to be signed to protect client - perf...
29,NaN,66,Unknown South Range structures,Pre Construction,Design,6.666667,5.000000,Med,Structural Engineer,Risk of discovering old basement causing issue...,NaN
30,NaN,67,Insufficient design detail from specialist CDP...,Pre Construction,Design,5.000000,1.666667,Low,Design Manager,Impacts the sign off planning conditions / li...,Regular design reviews and interface management
31,NaN,70,Satisfying EA requirements,Pre Construction,Design,1.666667,8.333333,Low,Environment Lead,Incident occurring which stops the work and a...,Waste management and compliance with the EA to...
32,NaN,72,Delay in design programme due to tenant/operat...,Pre Construction,Design,5.000000,5.000000,Med,Design Manager,Operator changes impacting on cost /\nprogramme,Recovery of cost / time included within the Ag...
33,NaN,73,Design changes (including client changes/ vari...,Construction,Design,10.000000,8.333333,High,Project Manager,Construction cost overrun,Traditional contract — risk with CYC; secure a...
34,NaN,75,Weather delays,Construction,Construction,8.333333,5.000000,Med,Project Manager,"Delay to programme - Wind, Temp, Rain",Contractor to provide impact and allowances vi...
35,NaN,76,Underpinning/ crack repairs by third parties,Construction,Structural,3.333333,8.333333,Med,Structural Engineer,Cracks may appear elsewhere. Remediation costs,"Detailed dilapidations surveys, crack monitors"
36,NaN,77,Ground conditions - Borehole survey depth insu...,Pre Construction,Design,5.000000,5.000000,Med,Lead Engineer,Proposed piling designs impacted by this and r...,"Additional bore hole surveys indertaken, no fo..."
37,NaN,80,Instability to boundary wall following demolition,Construction,Structural,5.000000,3.333333,Low,Structural Engineer,Structural works required (piers),Assessment of wall structure required - Scope ...
38,NaN,81,Clashes between the existing building foundati...,Pre Construction,Structural,5.000000,3.333333,Low,Lead Engineer,Co-ordination of drainage with foundations dur...,Trial holes could be undertaken to better unde...
39,NaN,82,Potential drainage clash with proposed lift sh...,Construction,Design,1.666667,5.000000,Low,Lead Engineer,Additional external drainage network,Trial hole dug in the location and appears to ...
40,NaN,83,Billing omissions or inaccuracies in BoQ,Pre Construction,Procurement,6.666667,8.333333,High,Project Manager,Missing information within the BoQ resulting i...,T&T have carried out reviews of the BoQ
41,NaN,84,Additional works not covered by contract docum...,Construction,Design,10.000000,8.333333,High,Project Manager,Cost & programme,Detailed change management process to be follo...
42,NaN,85,"Ongoing movement in the south range, given the...",Construction,Structural,3.333333,6.666667,Med,Structural Engineer,Underpinning works reinstated resulting in cos...,Monitoring during works
43,NaN,87,Design change due to level of development and ...,Pre Construction,Design,3.333333,3.333333,Low,Design Manager,Impact on cost and programme - changes may del...,Coordination to be managed by design team as a...
44,NaN,88,Council chamber cooling to be approved,Pre Construction,Design,3.333333,5.000000,Low,Design Manager,Revisit of design proposals - time and cost,Design team to coordinate with planning / cons...

In [30]:
doc3

,Date Added,Number,Risk Description,Project Stage,Project Category,Risk Owner,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)",Mitigating Action
0,NaN,ICT-001,Identity and Access Management (IAM) systems c...,Construction Operation,Cybersecurity,Infrastructure Manager,3,7,High,Implement automated IAM systems and Multiform ...
1,NaN,ICT-002,Backup and recovery services are not documente...,Construction Operation,Operational,Infrastructure Manager,9,7,Med,Implement automated IAM systems and Multiform ...
2,NaN,ICT-003,Critical Systems are supported by out of date ...,Construction Operation,Infrastructure Upgrade,Infrastructure Manager,10,7,High,Document and Test Backup and Recovery services...

In [31]:
doc4

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Mitigating Action,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)"
0,r1,opening of the moorgate cross rail station is ...,Pre Construction,Dependency,Project Manager,Regular engagement with\nCrossrail from now to...,6,2,low
1,r2,the riney highways contract is due to expire i...,Pre Construction,Contractor,Project Manager,Discussions to take place\ninternally should t...,4,2,low
2,r3,delays to the four developments surrounding th...,Construction,Dependency,Project Manager,Regular engagement with\ndevelopers from now u...,6,5,med
3,r4,infrastructure and utilities difficulties at t...,Construction,Infrastructure,Infrastructure Manager,Set expectations at the\nearliest stage possib...,6,8,med
4,r5,key stakeholder s do not endorse design options,Pre Construction,Stakeholder,Project Manager Environment Lead,Ensure that Stakeholder\nWorking Group is suit...,6,5,med
5,r6,delays changes to dependency projects such as ...,Construction,Dependency,Project Manager,Work with internal\nstakeholders to minimize\n...,6,5,med
6,r7,breakdown in engagement with key stakeholders ...,Pre Construction,Stakeholder,Project Manager Environment Lead,Ensure coherent\ncommunications with\nstakehol...,4,5,low
7,r8,tfl restructure may mean that no dedicated sch...,Pre Construction,Stakeholder,Project Manager,Officers will seek to\nestablish resources as ...,8,8,high
8,r9,there is a potential that the proposed scheme ...,Pre Construction,Social,Project Manager Environment Lead,Meetings with\nrepresentative groups will\nbe ...,2,5,low
9,r10,requirement to keep the ability for resilience...,Pre Construction,Design,Infrastructure Manager,Seek to ensure that an\nappropriate level of\n...,6,5,med

In [32]:
doc5

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Likelihood No Action (1-5),Impact No Action (1-5),"Risk Priority No Action (low, med, high)",Mitigating Action,Likelihood Current (1-5),Impact Current (1-5),"Risk Priority Current (low, med, high)"
0,1,legislative changes,Operations,Governance,Governance Officer,5,5,High,Use intelligence to Officers identify impendin...,5,2,Med
1,2,brexit,Operations,NaN,Head Of Corporate Services,5,5,High,Understanding and Government acting on passed ...,3,2,Med
2,3,failure of contractors and suppliers working o...,Operations,Governance,Corporate Management Team Lead,4,4,High,Regular monitoring The Leisure of contracts an...,4,3,Med
3,4,failure of it systems,Operations,IT,IT Manager,5,5,High,Effective auditing of GDPR systems and data he...,3,4,Med
4,5,insufficient staff to provide council services...,Operations,HR,Chief Executive Officer,5,4,High,Ensure all services All services have effectiv...,3,2,Med
5,6,breach of ict security causes loss of service,Operations,IT,IT Manager,5,5,High,Effective auditing of The Council systems and ...,3,4,Med
6,7,lack of access to council premises prevents se...,Operations,Emergency Planning,Emergency Planning Officer,5,5,High,Regularly test Emergency Emergency Plan testin...,3,2,Med
7,8,funding changes make council unsustainable,Operations,Finance,Head Of Finance,5,5,High,Using intelligence to We are model and plan fo...,3,3,Med
8,9,the council s ability to cope with a natural d...,Operations,Emergency Planning,Chief Executive,4,5,High,Regularly test Key senior Emergency Plan brief...,4,4,High
9,10,major health and safety incident,Operations,NaN,Chief Executive,4,4,High,Ensure health and A thorough safety is standar...,3,4,Med
10,11,fraud and error committed against the council,Operations,Finance,Head Of Internal Audit,4,5,High,Increase staff The Council vigilance National ...,3,3,Med
11,12,failure of external investment institutions,Operations,Finance,Investment Manager,4,5,High,Effective Treasury The Council’s Management re...,4,2,Med
12,13,failure of governance in major partners or in ...,Construction Operation,Governance,Governance Officer,5,4,High,The Annual Assurance that to Corporate governa...,3,3,Med
13,14,failure to achieve required savings targets,Operations,Finance,Chief Finance Officer,5,4,High,Robust control of Delivery corporate including...,3,3,Med
14,15,over run of major council projects in time or ...,Operations,Financial,Chief Executive Officer,5,4,High,Robust project Effective management. priority....,2,3,Med
15,16,service provision affected by organisational c...,Operations,Governance,Project Manager,5,4,High,Business continuity Plans plans for each servi...,4,3,Med
16,17,political changes in national priorities,Operations,NaN,Head Of Policy And Partnerships,4,5,High,Understanding and The risks acting on result i...,4,3,Med
17,18,capital funding strategy failure,Operations,Finance,Head Of Finance,4,5,High,Forward planning The Council’s and horizon reg...,3,3,Med
18,19,poor communications with stakeholders,Operations,Governance,Communications Officer,5,4,High,CSE Action Plan. The Council’s year by Staff s...,3,3,Med
19,20,commercial uncertainties associated with decis...,Operations,Finance,Corporate Management Team Lead,4,5,High,All governance The Council’s requirements have...,3,3,Med