In [37]:
import pandas as pd

In [38]:
doc4 = pd.read_csv('./data/generated_outputs/doc4.csv')
doc5 = pd.read_csv('./data/generated_outputs/doc5.csv')

In [39]:
doc4

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Mitigating Action,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)"
0,R1,Opening of the Moorgate\nCross rail station is...,Construction / Commissioning,Infrastructure,Project Manager,Regular engagement with\nCrossrail from now to...,6,2,low
1,R2,The Riney highways contract\nis due to expire ...,Pre-construction,Procurement,Construction Manager,Discussions to take place\ninternally should t...,4,2,low
2,R3,Delays to the four\ndevelopments surrounding\n...,Construction / Commissioning,Adjoining Owners,Project Manager,Regular engagement with\ndevelopers from now u...,6,5,med
3,R4,Infrastructure and utilities\ndifficulties at ...,Pre-construction,Infrastructure,Infrastructure Manager,Set expectations at the\nearliest stage possib...,6,8,med
4,R5,Key stakeholder(s) do not\nendorse design options,Pre-construction,Design,Project Manager,Ensure that Stakeholder\nWorking Group is suit...,6,5,med
5,R6,"Delays/changes to\ndependency projects, such\n...",Pre-construction,Infrastructure,Infrastructure Manager,Work with internal\nstakeholders to minimize\n...,6,5,med
6,R7,Breakdown in engagement\nwith key stakeholders...,Pre-construction,Adjoining Owners,Project Manager,Ensure coherent\ncommunications with\nstakehol...,4,5,low
7,R8,TfL restructure may mean that\nno dedicated sc...,Pre-construction,Planning,Infrastructure Manager,Officers will seek to\nestablish resources as ...,8,8,high
8,R9,There is a potential that the\nproposed scheme...,Pre-construction,Regulations,Environment Lead,Meetings with\nrepresentative groups will\nbe ...,2,5,low
9,R10,Requirement to keep the\nability for resilienc...,Pre-construction,Design,Infrastructure Manager,Seek to ensure that an\nappropriate level of\n...,6,5,med

In [40]:
doc5

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Likelihood No Action (1-10),Impact No Action (1-10),Mitigating Action,Likelihood Current (1-10),Impact Current (1-10),"Risk Priority (low, med, high)"
0,1,Legislative changes,Operation,Regulations,Governance Officer,5,5,Use intelligence to Officers identify impendin...,5,2,Low
1,2,Brexit,Operation,Regulations,Infrastructure Manager,5,5,Understanding and Government acting on passed ...,3,2,Low
2,3,Failure of contractors and suppliers working o...,Operation,Procurement,Infrastructure Manager,4,4,Regular monitoring The Leisure of contracts an...,4,3,Low
3,4,Failure of IT systems,Operations,Cybersecurity,IT Manager,5,5,Effective auditing of GDPR systems and data he...,3,4,Low
4,5,Insufficient staff to provide Council services...,Operation,HR,Infrastructure Manager,5,4,Ensure all services All services have effectiv...,3,2,Low
5,6,Breach of ICT security causes loss of service,Operations,Cybersecurity,IT Manager,5,5,Effective auditing of The Council systems and ...,3,4,Low
6,7,Lack of access to Council premises prevents se...,Operation,Services,Infrastructure Manager,5,5,Regularly test Emergency Emergency Plan testin...,3,2,Low
7,8,Funding changes make Council unsustainable,Operations,Financial,Infrastructure Manager,5,5,Using intelligence to We are model and plan fo...,3,3,Low
8,9,The Council’s ability to cope with a natural d...,Operation,Regulations,Infrastructure Manager,4,5,Regularly test Key senior Emergency Plan brief...,4,4,Low
9,10,Major health and safety incident,Operations,Regulations,Infrastructure Manager,4,4,Ensure health and A thorough safety is standar...,3,4,Low
10,11,Fraud and error committed against the Council,Operation,Financial,Infrastructure Manager,4,5,Increase staff The Council vigilance National ...,3,3,Low
11,12,Failure of external investment institutions,Operation,Financial,Infrastructure Manager,4,5,Effective Treasury The Council’s Management re...,4,2,Low
12,13,Failure of Governance in major partners or in ...,Operation,Governance,Governance Officer,5,4,The Annual Assurance that to Corporate governa...,3,3,Low
13,14,Failure to achieve required savings targets,Operations,Financial,Infrastructure Manager,5,4,Robust control of Delivery corporate including...,3,3,Low
14,15,Over-run of major Council projects in time or ...,Operations,Financial,Project Manager,5,4,Robust project Effective management. priority....,2,3,Low
15,16,Service provision affected by organisational c...,Operations,Services,Infrastructure Manager,5,4,Business continuity Plans plans for each servi...,4,3,Low
16,17,Political changes in national priorities,Operation,Regulations,Project Manager,4,5,Understanding and The risks acting on result i...,4,3,Low
17,18,Capital funding strategy failure,Operations,Financial,Infrastructure Manager,4,5,Forward planning The Council’s and horizon reg...,3,3,Low
18,19,Poor communications with stakeholders,Operations,Governance,Project Manager,5,4,CSE Action Plan. The Council’s year by Staff s...,3,3,Low
19,20,Commercial uncertainties associated with decis...,Operation,Financial,Infrastructure Manager,4,5,All governance The Council’s requirements have...,3,3,Low