In [1]:
import pandas as pd

In [2]:
doc4 = pd.read_csv('./data/generated_outputs/doc4.csv')
doc5 = pd.read_csv('./data/generated_outputs/doc5.csv')

In [3]:
doc4

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Mitigating Action,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)"
0,R1,Opening of the Moorgate\nCross rail station is...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,R2,The Riney highways contract\nis due to expire ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R3,Delays to the four\ndevelopments surrounding\n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R4,Infrastructure and utilities\ndifficulties at ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R5,Key stakeholder(s) do not\nendorse design options,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R6,"Delays/changes to\ndependency projects, such\n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,R7,Breakdown in engagement\nwith key stakeholders...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,R8,TfL restructure may mean that\nno dedicated sc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,R9,There is a potential that the\nproposed scheme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,R10,Requirement to keep the\nability for resilienc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
doc5

,Risk ID,Risk Description,Project Stage,Project Category,Risk Owner,Mitigating Action No Action,Mitigating Action Current,Likelihood No Action (1-10),Impact No Action (1-10),Likelihood Current (1-10),Impact Current (1-10),"Risk Priority (low, med, high)"
0,1,Legislative changes,NaN,NaN,NaN,Monitoring Officer Horizon scanning by Legal/C...,Increase staff The Council vigilance National ...,5,5,3,3,NaN
1,2,Brexit,NaN,NaN,NaN,Horizon scanning by Legal Services / CMT / Hea...,Effective Treasury The Council’s Management re...,5,5,4,2,NaN
2,3,Failure of contractors and suppliers working o...,NaN,NaN,NaN,Procurement processes – including financial as...,The Annual Assurance that to Corporate governa...,4,4,3,3,NaN
3,4,Failure of IT systems,NaN,NaN,NaN,Data protection policy and procedure Freedom o...,Robust control of Delivery corporate including...,5,5,3,3,NaN
4,5,Insufficient staff to provide Council services...,NaN,NaN,NaN,Learning & Development framework / Training Wo...,Robust project Effective management. priority....,5,4,2,3,NaN
5,6,Breach of ICT security causes loss of service,NaN,NaN,NaN,Anti-virus software Geographically distributed...,Business continuity Plans plans for each servi...,5,5,4,3,NaN
6,7,Lack of access to Council premises prevents se...,NaN,NaN,NaN,Alarm and security systems Fire drills Busines...,Understanding and The risks acting on result i...,5,5,4,3,NaN
7,8,Funding changes make Council unsustainable,NaN,NaN,NaN,S151/ Chief Finance Officer Financial Regulati...,Forward planning The Council’s and horizon reg...,5,5,3,3,NaN
8,9,The Council’s ability to cope with a natural d...,NaN,NaN,NaN,Emergency plan Emergency planning exercises be...,CSE Action Plan. The Council’s year by Staff s...,4,5,3,3,NaN
9,10,Major health and safety incident,NaN,NaN,NaN,Health & Safety (H&S) Panel H&S procedures – a...,All governance The Council’s requirements have...,4,4,3,3,NaN