In [1]:
import pandas as pd

In [9]:
df1 = pd.read_csv('./data/preprocessed_inputs/df1.csv')
df2 = pd.read_csv('./data/preprocessed_inputs/df2.csv')
df3 = pd.read_csv('./data/preprocessed_inputs/df3.csv')
df4 = pd.read_csv('./data/preprocessed_inputs/df4.csv')
df5 = pd.read_csv('./data/preprocessed_inputs/df5.csv')

In [10]:
df1

,Budget Period,Revision Date,RBS Level 1,RBS Level 2,Risk Name,TRL,TPL,Technology Life Phase,Risk Owner,Baseline +/-,...,Response Strategy,Response Description,Response Timing,Residual SEV,Residual FRQ,Residual RPN,Residual Description,Secondary Risks,Recommendations & Action Items,Contingency Plan
0,budget period 1,2017 02 21,external,4 6 regulatory,task 2 2 smolt probability of encounter model ...,7.0,7.0,NaN,n johnson environmental,NaN,...,mitigate,facilitate conversations with umaine on data s...,now,1.0,3.0,3.0,if data is not shared move on to next step of ...,NaN,n johnson to continue to faciliate conversatio...,continue environmental monitoring plan develop...
1,budget period 1,2017 02 21,external,4 9 external stakeholder,task 5 ice data collected,7.0,7.0,NaN,j kasper uaa lead,NaN,...,mitigate,real time data collection implemented,now,2.0,1.0,2.0,if real time data collection is not successful...,increased complexity,uaf to take lead on techical side m worthingto...,redesign ice study equipment for oper water te...
2,budget period 2,2017 02 21,external,4 6 regulatory,permitting licensing complete for in water tes...,7.0,7.0,multiple or all life phases,n johnson environmental,NaN,...,avoid,ferc final license application submittal scheu...,now,4.0,3.0,12.0,ferc license not granted in time,schedule slip budget creep,initiate communication with regulatory agencie...,consider operating under verdant exemption for...
3,budget period 2,2017 02 21,technical,1 5 technology,generator final design,7.0,7.0,design,r tyler lead engineer,NaN,...,mitigate,design reviews and component validation testing,before design finalized,3.0,2.0,NaN,manufactured product is stil out of specificaiton,increased cost schedule slip,work closeley with generator vendor to develop...,refurbish and reuse exisitng generator
4,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,generator procurement,7.0,7.0,assembly and commissioning,r tyler lead engineer,NaN,...,avoid,ensure generator delivery by 2 2018 to allow a...,before manufacturing,3.0,3.0,9.0,generator has manufacturing or integration iss...,increased effort and cost,continue communication with ikm and orpc irela...,refurbish and reuse exisitng generator
5,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,buoyancy system procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,compile bom and ascertain component lead times...,before po issued,3.0,1.0,3.0,unexepcted component shortage,NaN,use cots components,delay buoyancy system validation tests
6,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,structural assembly procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,mitigate,frequent vendor communication issue po with ro...,before po issued,3.0,2.0,6.0,unexpected fabrication delays,increased cost and effort,freqent vendor communications contract include...,delay full system validation tests
7,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,turbine procuement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,mitigate,frequent vendor communication issue po with ro...,before po issued,3.0,2.0,6.0,unexpected fabrication delays,increased cost and effort,freqent vendor communications contract include...,delay full system validation tests
8,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,power electronics procurement,7.0,7.0,multiple or all life phases,m worthington project management,NaN,...,mitigate,frequent vendor communication issue po with ro...,now,3.0,3.0,9.0,unexpected design fabrication fat delays,increased cost and effort,freqent vendor communications contract include...,delay laboratory validation
9,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,scada procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,compile bom and ascertain component lead times...,before po issued,3.0,3.0,9.0,unexepcted component shortage personel shortag...,NaN,use cots components start acada development early,delay scada system validation tests
10,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,power and data cable procurement,7.0,7.0,multiple or all life phases,m worthington project management,NaN,...,mitigate,compile bom and ascertain component lead times...,before po issued,3.0,3.0,NaN,unexepcted component shortage,NaN,use cots components where possible,delay power and data cable validation tests
11,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,mooring sytem procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,compile bom and ascertain component lead times...,before po issued,3.0,1.0,3.0,unexepcted component shortage,NaN,use cots components,delay moorins system validation tests
12,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,dirveline procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,mitigate,frequent vendor communication issue po with ro...,before po issued,3.0,2.0,6.0,unexpected fabrication delays,increased cost and effort,freqent vendor communications contract include...,delay full system validation tests
13,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,mechanical brake procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,mitigate,frequent vendor communication issue po with ro...,before po issued,3.0,2.0,6.0,unexpected fabrication delays,increased cost and effort,freqent vendor communications contract include...,delay mechanical brake validation tests
14,budget period 2,2017 02 21,commercial,3 3 suppliers and vendors,mechanical brake procurement,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,mitigate,frequent vendor communication issue po with ro...,before po issued,3.0,2.0,6.0,unexpected fabrication delays,increased cost and effort,freqent vendor communications contract include...,delay mechanical brake validation tests
15,budget period 2,2017 02 21,technical,1 5 technology,buoyancy system validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,utilizing incremetnal improvements to a proven...,before assembly and commissioning,3.0,2.0,6.0,unexpected component failure after validation ...,increased cost and effort,clearly scope validation tests to ensure tests...,secondary redundant isolated recovery system a...
16,budget period 2,2017 02 21,technical,1 5 technology,structural assembly validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,fea analysis of structure include load factors...,before assembly and commissioning,3.0,2.0,6.0,unexpcted structural failure,additional desing work materials or strucutral...,complete thorough design and analysis desing t...,utilize local resources to effect repair and o...
17,budget period 2,2017 02 21,technical,1 5 technology,turbine validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,utilize cfd as design tool for performance val...,before assembly and commissioning,3.0,2.0,6.0,unexpected turbine failure,increased cost added structural elements could...,thorough design and analysis utilizing third p...,accept lower power output system removal inspe...
18,budget period 2,2017 02 21,technical,1 5 technology,generator validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,factory accpetance testing and laboratory test...,before assembly and commissioning,3.0,2.0,6.0,unexpected generator failure,increased cost schedule slip possible,ensure adequate factory acceptance testing and...,refurbish and reuse protptype generator while ...
19,budget period 2,2017 02 21,technical,1 5 technology,power electronics validation,7.0,7.0,multiple or all life phases,m worthington project management,NaN,...,avoid,factory accpetance tests and sequenced laborat...,before assembly and commissioning,3.0,3.0,9.0,unexpected power electonics failure or grid in...,incresed cost schedule slip possible,adequate factory acceptance tests thorough lab...,dissipate power through secondary load bank or...
20,budget period 2,2017 02 21,technical,1 5 technology,scada validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,factory accpetance tests and sequenced laborat...,before assembly and commissioning,3.0,3.0,9.0,unexpected scada failure or communciations issues,increased cost,adequate bench tests through full length power...,operate with simplified control system remove ...
21,budget period 2,2017 02 21,technical,1 5 technology,power and data cable validation,7.0,7.0,multiple or all life phases,m worthington project management,NaN,...,avoid,utilize proven cable technology utilize second...,before assembly and commissioning,4.0,2.0,8.0,unexpected power and data cable failure,increased cost and operational complexity incr...,ensure cable meets specs test full length cabl...,replace power and data cable
22,budget period 2,2017 02 21,technical,1 5 technology,mooring sytem validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,design to dnv standards utilize geophyisical k...,before assembly and commissioning,5.0,2.0,10.0,unexpected mooring system failure,increased size and operational complexity as a...,utilize industry expertise to guide mooring sy...,allow anchor slip as favorable failure mode re...
23,budget period 2,2017 02 21,technical,1 5 technology,dirveline validation,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,throught validation testing desing system for ...,before assembly and commissioning,4.0,3.0,12.0,unexpected direvline failure,incresed cost,complete thorough validation testing and incor...,validation tests in advance of system build le...
24,budget period 2,2017 02 21,technical,1 5 technology,mechanical brake,7.0,7.0,multiple or all life phases,r tyler lead engineer,NaN,...,avoid,throught validation testing redundant electric...,before assembly and commissioning,3.0,3.0,9.0,unexpected mechanical brake failure,incresed cost and complexity,complete thorough validation testing including...,use electrical brake or remove system from cur...
25,budget period 3,2017 02 24,external,4 6 regulatory,receipt of all permits and licesenses,NaN,NaN,multiple or all life phases,n johnson environmental,NaN,...,avoid,continue regular dialogue with regulatory agen...,december,5.0,3.0,15.0,uncertainity with regurlatory agency approvals...,increased cost and effort,manage personnel time and availablity accordingly,move forward under verdant exemption secure ne...
26,budget period 3,2017 02 24,management,2 1 project management,component delivery to igiugig,7.0,7.0,transportation,m worthington project management,NaN,...,mitigate,track project schedule align component validat...,before assembly and commissioning,4.0,2.0,8.0,unexcepcted or uncontrollabel circumstances le...,increased cost and effort,track shipment continuously,delay deployment to 2019 if component delivery...
27,budget period 3,2017 02 24,technical,1 6 technical interfaces,device assmebly,7.0,7.0,assembly and commissioning,r tyler lead engineer,NaN,...,mitigate,device assembly is fdifficult or requires work...,june,4.0,2.0,8.0,preassembl as many components as possible prio...,increased cost and effort,include device assembly in validation with as ...,perfrom redesign and modifcation work in igiug...
28,budget period 3,2017 02 24,technical,1 7 system reliability,power system comissioning issues,7.0,7.0,assembly and commissioning,m worthington project management,NaN,...,mitigate,prior device testing and component testing in ...,august,5.0,2.0,10.0,per shipment validation work in nikiksi with d...,testing may cause damge to components increase...,test all components in configuration for igiug...,resolove issues with locally available resourc...
29,budget period 3,2017 02 24,technical,1 7 system reliability,complications with winter ice,6.0,6.0,extreme events,r tyler lead engineer,NaN,...,mitigate,collection of in river ice data for 2 years pr...,june,5.0,3.0,15.0,uncertiainty of ice interaction or in river fo...,increased cost and effort,perform thorough analysis of ice data from in ...,remove divce from irver if possible or curtail...
30,budget period 3,2017 02 24,external,4 4 environmental weather,adverse salmon smolt interactions,6.0,6.0,normal power production,n johnson environmental,NaN,...,mitigate,develop rigorous fish monitroing pland in budg...,may,4.0,3.0,12.0,lack of established industry standard for smol...,incresed cost without eliminating or adequtely...,establish adaptive management plan with agenci...,stop device operations during smolt outmigrati...
31,budget period 3,2017 02 24,technical,1 7 system reliability,device removal complications,7.0,7.0,decommissioning,m worthington project management,NaN,...,mitigate,buoyancy system includes redundant and isoalte...,may,5.0,2.0,10.0,redundant pretested systems reduce likleihood ...,increased cost and effort increase system comp...,document results of pre testing in nikiksi vis...,utilize locaaly available resources to develop...
32,budget period 3,2017 02 24,commercial,3 3 suppliers and vendors,higher cost for maintenance and logistical sup...,7.0,6.0,normal power production,m worthington project management,NaN,...,mitigate,developing system requirements will be critica...,before assembly and commissioning,2.0,2.0,4.0,higher cost risk should be lessened,complex supply chain and remote area logistics...,structure contract to include incentives penal...,follow contractual provisions for higher costs...

In [11]:
df2

,Risk ID,Risk Description,Impact,Project Stage,Risk Category,Likelihood (1-10),Impact (1-10),Risk Index,Risk Owner,Mitigation
0,3,failure to discharge planning and listed build...,NaN,pre construction,planning,3.333333,1.666667,2.0,project manager,design team and contractor to collate initial ...
1,4,planning conditions impact on budget,increase project budget,pre construction,planning,6.666667,5.000000,14.0,project manager,extent of conditions known and to be reviewed ...
2,10,electricity provider works delayed or non conf...,works to provide new supply are delayed not in...,construction,legislation,3.333333,3.333333,4.0,project manager,orders for the electrical services have been p...
3,11,building control sign off delay due to lack of...,revisit design to address concerns of building...,construction commissioning,legislation,3.333333,3.333333,4.0,project manager,continue liaison with the building control off...
4,12,impact of boat companies city cruises,impact delivery site servicing strategy,construction,planning,3.333333,1.666667,2.0,project manager,legal agreements are in place
5,13,party wall negotiations construction access,objection from neighbours potential delay to p...,pre construction,planning,5.000000,6.666667,10.5,project manager,appoint party wall surveyor and progress discu...
6,14,failure to secure market interest for restaura...,restaurant not achieving appropriate tenant an...,pre construction operation,procurement,5.000000,8.333333,15.0,project manager,early engagement of agent for potential lettin...
7,16,increased construction costs,exchange rate on materials impact of internati...,construction,procurement,5.000000,5.000000,9.0,project manager,tender prices received and under review risk s...
8,18,sub contractor insolvency,impacts main contractor,construction,procurement,6.666667,5.000000,12.0,construction manager,contractor financial checks and vetting of sub...
9,20,surveys required to determine ground condition...,possible need to re visit design deal with con...,pre construction,surveys,1.666667,8.333333,3.0,lead engineer,gi survey undertaken information obtained cont...
10,21,identification of active movement,proven to be active remediation impacts cost,pre construction,surveys,1.666667,8.333333,5.0,structural engineer,ongoing monitoring by arup and monitoring spec...
11,22,unidentified archaeology,further evaluation required cost impact,pre construction,surveys,3.333333,3.333333,4.0,environment lead,evaluation of site undertaken
12,23,additional surveys required,cost impact,pre construction,surveys,1.666667,1.666667,1.0,project manager,undertake outstanding surveys
13,26,unrealistic programme submitted by contractor,NaN,pre construction,programme,1.666667,5.000000,2.5,project manager,market tested
14,27,programme delays due to flood levels impacting...,works stop cost and programme implications,construction,programme,10.000000,8.333333,24.0,project manager environment lead,review historic flood data and issue to contra...
15,29,delay to design programme,client contractor impact cost programme,pre construction,design,5.000000,5.000000,9.0,design manager,implementation of irs schedules design deliver...
16,31,underpinning piling and crack repairs to be co...,may resolve existing cracks and movement of th...,pre construction,design,5.000000,8.333333,15.0,structural engineer,detailed dilapidations surveys crack monitors
17,32,discovering structural unknowns,costs of additional surveys and remediation works,construction,design,8.333333,6.666667,17.5,structural engineer,undertake surveys early to determine unknowns ...
18,35,undetected services not identified on surveys ...,programme re design cost impact to address unk...,construction,services,3.333333,5.000000,6.0,lead engineer,utilities surveys maps obtained and plotted on...
19,40,river source heat pump license approval by the...,delay in no approval from ea,pre construction,services,1.666667,6.666667,4.5,environment lead,provisional consent obtained continued dialogu...
20,41,sourcing stone for remediation works,quarry that stone exists from is closed impact...,construction,materials,6.666667,5.000000,12.0,procurement manager,investigate other quarries which supply the st...
21,42,structural damage and the repairs required to ...,finding the right solution to undertake the un...,construction,construction,6.666667,6.666667,14.0,structural engineer,bullivants arup design and vinci temporary wor...
22,48,outstanding defects remaining unresolved,cyc left with legacy issues and building defec...,commissioning,post contract,3.333333,5.000000,4.0,project manager,ability to resolve within the building contrac...
23,50,costs exceeds allocated budget non constructio...,particular risks surrounding consultant fees f...,construction commissioning,financial,8.333333,5.000000,15.0,project manager,review non construction costs prior to contrac...
24,51,incorrect estimation design errors and ambigui...,construction cost overrun,pre construction,financial,5.000000,5.000000,9.0,design manager,risk sits with cyc except cdp items
25,56,availability of specialist labour equipment,change in specification need to appoint specia...,construction,construction,5.000000,5.000000,9.0,project manager,dialogue with main contractor supply chain
26,61,poor co ordination with design team interfaces...,NaN,construction,design,3.333333,5.000000,6.0,design manager,cdp requirements have reduced from initial int...
27,62,rights of light,NaN,pre construction,adjoining owners,1.666667,6.666667,2.5,project manager,title report does not identify any issues
28,64,poor contractor performance during construction,NaN,construction,construction,3.333333,8.333333,9.0,project manager,contract to be signed to protect client perfor...
29,66,unknown south range structures,risk of discovering old basement causing issue...,construction,design,6.666667,5.000000,12.0,structural engineer,NaN
30,67,insufficient design detail from specialist cdp...,impacts the sign off planning conditions liste...,pre construction,design,5.000000,1.666667,6.0,design manager,regular design reviews and interface management
31,70,satisfying ea requirements,incident occurring which stops the work and ac...,pre construction,design,1.666667,8.333333,4.5,environment lead,waste management and compliance with the ea to...
32,72,delay in design programme due to tenant operat...,operator changes impacting on cost programme,pre construction,design,5.000000,5.000000,9.0,design manager,recovery of cost time included within the agre...
33,73,design changes including client changes variat...,construction cost overrun,construction,financial,10.000000,8.333333,30.0,project manager,traditional contract risk with cyc secure adeq...
34,75,weather delays,delay to programme wind temp rain,construction,construction,8.333333,5.000000,12.5,project manager,contractor to provide impact and allowances vi...
35,76,underpinning crack repairs by third parties,cracks may appear elsewhere remediation costs,construction,design,3.333333,8.333333,10.0,structural engineer,detailed dilapidations surveys crack monitors
36,77,ground conditions borehole survey depth insuff...,proposed piling designs impacted by this and r...,pre construction,surveys,5.000000,5.000000,9.0,lead engineer,additional bore hole surveys indertaken no fou...
37,80,instability to boundary wall following demolition,structural works required piers,construction,design,5.000000,3.333333,6.0,structural engineer,assessment of wall structure required scope of...
38,81,clashes between the existing building foundati...,co ordination of drainage with foundations dur...,construction,surveys,5.000000,3.333333,7.5,lead engineer,trial holes could be undertaken to better unde...
39,82,potential drainage clash with proposed lift sh...,additional external drainage network,construction,surveys,1.666667,5.000000,3.0,lead engineer,trial hole dug in the location and appears to ...
40,83,billing omissions or inaccuracies in boq,missing information within the boq resulting i...,pre construction,financial,6.666667,8.333333,18.0,project manager,t t have carried out reviews of the boq
41,84,additional works not covered by contract docum...,cost programme,construction,financial,10.000000,8.333333,27.0,project manager,detailed change management process to be followed
42,85,ongoing movement in the south range given the ...,underpinning works reinstated resulting in cos...,construction operation,design,3.333333,6.666667,8.0,structural engineer,monitoring during works
43,87,design change due to level of development and ...,impact on cost and programme changes may delay...,pre construction,design,3.333333,3.333333,5.0,design manager,coordination to be managed by design team as a...
44,88,council chamber cooling to be approved,revisit of design proposals time and cost,commissioning,design,3.333333,5.000000,6.0,design manager,design team to coordinate with planning conser...

In [12]:
df3

,Number,Risk Description,Probability,Severity,Score,Risk Owner,Action Plan
0,ict 001,identity and access management iam systems com...,3,7,high,NaN,implement automated iam systems and multiform ...
1,ict 002,backup and recovery services are not documente...,9,7,med,infrastructure manager,implement automated iam systems and multiform ...
2,ict 003,critical systems are supported by out of date ...,10,7,high,infrastructure manager,document and test backup and recovery services...

In [13]:
df4

,Risk ID,Risk Description,Likelihood (1-10),Impact (1-10),"Risk Priority (low, med, high)",Mitigating Action
0,r1,opening of the moorgate cross rail station is ...,possible,minor,low,regular engagement with crossrail from now to ...
1,r2,the riney highways contract is due to expire i...,unlikely,minor,low,discussions to take place internally should th...
2,r3,delays to the four developments surrounding th...,possible,serious,med,regular engagement with developers from now un...
3,r4,infrastructure and utilities difficulties at t...,possible,major,med,set expectations at the earliest stage possibl...
4,r5,key stakeholder s do not endorse design options,possible,serious,med,ensure that stakeholder working group is suitably
5,r6,delays changes to dependency projects such as ...,possible,serious,med,work with internal stakeholders to minimize an...
6,r7,breakdown in engagement with key stakeholders ...,unlikely,serious,low,ensure coherent communications with stakeholde...
7,r8,tfl restructure may mean that no dedicated sch...,likely,major,high,officers will seek to establish resources as e...
8,r9,there is a potential that the proposed scheme ...,rare,serious,low,meetings with representative groups will be co...
9,r10,requirement to keep the ability for resilience...,possible,serious,med,seek to ensure that an appropriate level of re...

In [14]:
df5

,Reference,Risk,Effects,Risk_if_No_Action_Impact,Risk_if_No_Action_Likelihood,Risk_if_No_Action_Score,Mitigation,Current_Risk_Impact,Current_Risk_Likelihood,Current_Risk_Score,Risk_Owner,Actions_Being_Taken,Comments_and_Progress
0,1,legislative changes,changes arising from central government or eu ...,5,5,25,monitoring officer horizon scanning by legal c...,2,5,10,carol pilson,use intelligence to officers identify impendin...,continue to horizon scan for legislative and t...
1,2,brexit,uncertainty during transition period followed ...,5,5,25,horizon scanning by legal services cmt heads o...,2,3,6,peter catchpole carol pilson,understanding and government acting on passed ...,withdrawal agreement bill has been lessening t...
2,3,failure of contractors and suppliers working o...,failure of contractor or partners to deliver s...,4,4,16,procurement processes including financial aspe...,3,4,12,cmt,regular monitoring the leisure of contracts an...,service was outsourced in december included wi...
3,4,failure of it systems,failure to secure and manage data leads to los...,5,5,25,data protection policy and procedure freedom o...,4,3,12,carol pilson peter catchpole,effective auditing of gdpr systems and data he...,is live see risk 1 internet feed to fenland ha...
4,5,insufficient staff to provide council services...,constraints to effective workforce planning le...,4,5,20,learning development framework training workin...,2,3,6,cmt,ensure all services all services have effectiv...,have published service plans learning and work...
5,6,breach of ict security causes loss of service,major it physical hardware failure or electron...,5,5,25,anti virus software geographically distributed...,4,3,12,peter catchpole,effective auditing of the council systems and ...,has subscribed to the national cyber centre s ...
6,7,lack of access to council premises prevents se...,disruption of service provision,5,5,25,alarm and security systems fire drills busines...,2,3,6,peter catchpole,regularly test emergency emergency plan testin...,plans ongoing programme of review and training...
7,8,funding changes make council unsustainable,economic changes imposed savings requirements ...,5,5,25,s151 chief finance officer financial regulatio...,3,3,9,peter catchpole,using intelligence to we are model and plan fo...,closely watching local government finance coun...
8,9,the council s ability to cope with a natural d...,natural disaster malicious or accidental incid...,5,4,20,emergency plan emergency planning exercises be...,4,4,16,cmt,regularly test key senior emergency plan brief...,staff attend regular multi agency and planning...
9,10,major health and safety incident,major health safety incident at council leads ...,4,4,16,health safety h s panel h s procedures address...,4,3,12,cmt,ensure health and a thorough safety is standar...,health and safety regime at the ensures that t...
10,11,fraud and error committed against the council,potential for fraud corruption malpractice or ...,5,4,20,anti fraud corruption policy strategy financia...,3,3,9,peter catchpole carol pilson,increase staff the council vigilance national ...,has assisted with each annual fraud initiative...
11,12,failure of external investment institutions,failure of external investment institutions af...,5,4,20,policy for maximum investment borrowing levels...,2,4,8,peter catchpole,effective treasury the council s management re...,treasury management position is reviewed and i...
12,13,failure of governance in major partners or in ...,partnership governance not adopted or followed...,4,5,20,fsp fenland public service board cabinet and o...,3,3,9,carol pilson peter catchpole,the annual assurance that to corporate governa...,governance statement being reported governance...
13,14,failure to achieve required savings targets,failure to achieve efficiency saving maximise ...,4,5,20,heightened analysis of budgets and services by...,3,3,9,cmt,robust control of delivery corporate including...,of council efficiency targets continue deliver...
14,15,over run of major council projects in time or ...,failure to manage projects effectively leads t...,4,5,20,project management methodology contract standi...,3,2,6,cmt,robust project effective management priority e...,project management remains a council projects ...
15,16,service provision affected by organisational c...,service provision and performance affected by ...,4,5,20,working environment org culture staff committe...,3,4,12,peter catchpole,business continuity plans plans for each servi...,regularly checked and tested have reviewed the...
16,17,political changes in national priorities,changes in national political priorities may r...,5,4,20,financial workforce planning monitoring by cmt...,3,4,12,paul medd,understanding and the risks acting on result i...,of legislative change remain high as a of the ...
17,18,capital funding strategy failure,financial risks of capital funding shortfalls ...,5,4,20,asset mgt plan asset disposal linked to capita...,3,3,9,peter catchpole,forward planning the council s and horizon reg...,capital funding programme is reviewed by offic...
18,19,poor communications with stakeholders,poor communication with stakeholders and staff...,4,5,20,internal and external regular publications sta...,3,3,9,carol pilson,cse action plan the council s year by staff su...,cse performance is assessed each an external e...
19,20,commercial uncertainties associated with decis...,reputational damage financial loss impact on s...,5,4,20,robust oversight and governance arrangements e...,3,3,9,cmt,all governance the council s requirements have...,risk appetite is currently being risk will be ...